// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf-f5zspyWbF4mmWpD_yBz5BLmPuJziUk',
    appId: '1:895089513202:web:9069e7c60426f4d843366b',
    messagingSenderId: '895089513202',
    projectId: 'practicamovil-seg',
    authDomain: 'practicamovil-seg.firebaseapp.com',
    storageBucket: 'practicamovil-seg.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvleuC-Uxx0juahSGpMag4gUyHKbhkVdQ',
    appId: '1:895089513202:android:3b4d45179c2bb54243366b',
    messagingSenderId: '895089513202',
    projectId: 'practicamovil-seg',
    storageBucket: 'practicamovil-seg.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBf-f5zspyWbF4mmWpD_yBz5BLmPuJziUk',
    appId: '1:895089513202:web:6a080b79f6a2574b43366b',
    messagingSenderId: '895089513202',
    projectId: 'practicamovil-seg',
    authDomain: 'practicamovil-seg.firebaseapp.com',
    storageBucket: 'practicamovil-seg.firebasestorage.app',
  );
}
